/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ınterfaceprojem;

/**
 *
 * @author Berkant
 */
public class Notgörüntüleme extends javax.swing.JFrame {
    
    /**
     * Creates new form Notgörüntüleme
     */
    public Notgörüntüleme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 234, 350, 20);

        jLabel2.setText("FİZ107          PHYSİCS 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 130, 350, 20);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 154, 350, 20);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 184, 350, 20);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 210, 350, 20);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 260, 350, 20);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 284, 350, 20);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 310, 350, 20);

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 334, 350, 20);

        jLabel16.setText("100");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(400, 136, 40, 14);

        jLabel17.setText("50");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(400, 160, 40, 20);

        jLabel18.setText("40");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(400, 184, 40, 20);

        jLabel19.setText("70");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(400, 210, 40, 20);

        jLabel20.setText("80");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(400, 240, 30, 14);

        jLabel21.setText("95");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(400, 260, 40, 20);

        jLabel22.setText("66");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(400, 284, 40, 20);

        jLabel23.setText("20");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(400, 310, 40, 20);

        jLabel24.setText("0");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(400, 334, 40, 20);

        jLabel11.setText("50");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(470, 136, 40, 20);

        jLabel12.setText("100");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(470, 160, 40, 14);

        jLabel13.setText("50");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(470, 180, 20, 20);

        jLabel14.setText("85");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(470, 210, 30, 20);

        jLabel15.setText("65");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(470, 240, 40, 15);

        jLabel25.setText("75");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(470, 260, 40, 20);

        jLabel26.setText("45");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(470, 290, 20, 15);

        jLabel27.setText("45");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(472, 310, 20, 20);

        jLabel28.setText("100");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(468, 334, 30, 20);

        jLabel29.setText("CB");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(540, 134, 20, 20);

        jLabel30.setText("AA");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(540, 160, 30, 15);

        jLabel31.setText("AA");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(540, 184, 20, 20);

        jLabel32.setText("AA");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(540, 210, 30, 15);

        jLabel33.setText("BB");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(540, 240, 30, 15);

        jLabel34.setText("FF");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(540, 264, 30, 15);

        jLabel35.setText("BB");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(540, 290, 30, 15);

        jLabel36.setText("BB");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(540, 310, 30, 20);

        jLabel37.setText("BA");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(540, 334, 30, 20);

        jLabel38.setText("70");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(630, 140, 30, 10);

        jLabel39.setText("40");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(630, 160, 30, 15);

        jLabel40.setText("40");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(630, 190, 30, 10);

        jLabel41.setText("65");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(630, 214, 30, 15);

        jLabel42.setText("70");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(630, 240, 30, 15);

        jLabel43.setText("85");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(630, 264, 30, 20);

        jLabel44.setText("25");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(630, 290, 30, 15);

        jLabel45.setText("30");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(630, 314, 30, 15);

        jLabel46.setText("85");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(630, 334, 30, 20);

        jLabel47.setText("GEÇTİ");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(700, 140, 50, 10);

        jLabel48.setText("GEÇTİ");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(700, 160, 40, 15);

        jLabel49.setText("GEÇTİ");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(700, 185, 40, 20);

        jLabel50.setText("GEÇTİ");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(700, 210, 50, 20);

        jLabel51.setText("GEÇTİ");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(700, 240, 40, 10);

        jLabel52.setText("GEÇTİ");
        getContentPane().add(jLabel52);
        jLabel52.setBounds(700, 260, 50, 20);

        jLabel53.setText("GEÇTİ");
        getContentPane().add(jLabel53);
        jLabel53.setBounds(700, 290, 50, 15);

        jLabel54.setText("GEÇTİ");
        getContentPane().add(jLabel54);
        jLabel54.setBounds(700, 310, 50, 20);

        jLabel55.setText("GEÇTİ");
        getContentPane().add(jLabel55);
        jLabel55.setBounds(700, 335, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ınterfaceprojem/notliste.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 4, 780, 350);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 356, 780, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notgörüntüleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notgörüntüleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notgörüntüleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notgörüntüleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Notgörüntüleme a=new Notgörüntüleme();
                a.setVisible(true);
                a.setSize(790,400);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
