/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication302;

/**
 *
 * @author Berkant
 */
public class öğrenciBilgi extends javax.swing.JFrame {

    /**
     * Creates new form öğrenciBilgi
     */
    public öğrenciBilgi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nolabel = new javax.swing.JLabel();
        tclabel = new javax.swing.JLabel();
        adlabel = new javax.swing.JLabel();
        sınıflabel = new javax.swing.JLabel();
        fakultelabel = new javax.swing.JLabel();
        bolumlabel = new javax.swing.JLabel();
        programlabel = new javax.swing.JLabel();
        donemlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(640, 10, 90, 80);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 51));
        jButton1.setText("Not Listesi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 300, 120, 23);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("Ders Programı");
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 340, 120, 23);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setText("Akademik Takvim");
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 420, 120, 23);

        jButton4.setForeground(new java.awt.Color(0, 51, 255));
        jButton4.setText("Yönetmelik");
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 460, 120, 23);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 51));
        jButton5.setText("GANO Hesapla");
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 380, 120, 23);

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 70, 230, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ınterfaceprojem/566feebe67b0a91094a81592.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 170, 600, 350);

        nolabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nolabel.setForeground(new java.awt.Color(255, 255, 255));
        nolabel.setText("20160807013");
        getContentPane().add(nolabel);
        nolabel.setBounds(130, 0, 100, 30);

        tclabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tclabel.setForeground(new java.awt.Color(255, 255, 255));
        tclabel.setText("35428950354");
        getContentPane().add(tclabel);
        tclabel.setBounds(130, 30, 100, 20);

        adlabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adlabel.setForeground(new java.awt.Color(255, 255, 255));
        adlabel.setText("Berkant GÜNEŞ");
        adlabel.setToolTipText("");
        getContentPane().add(adlabel);
        adlabel.setBounds(130, 50, 130, 30);

        sınıflabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sınıflabel.setForeground(new java.awt.Color(255, 255, 255));
        sınıflabel.setText("2");
        getContentPane().add(sınıflabel);
        sınıflabel.setBounds(130, 86, 50, 15);

        fakultelabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fakultelabel.setForeground(new java.awt.Color(255, 255, 255));
        fakultelabel.setText("Mühendislik Fakültesi");
        getContentPane().add(fakultelabel);
        fakultelabel.setBounds(390, 0, 260, 20);

        bolumlabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bolumlabel.setForeground(new java.awt.Color(255, 255, 255));
        bolumlabel.setText("Bilgisayar Mühendisliği");
        bolumlabel.setToolTipText("");
        getContentPane().add(bolumlabel);
        bolumlabel.setBounds(390, 20, 270, 30);

        programlabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        programlabel.setForeground(new java.awt.Color(255, 255, 255));
        programlabel.setText("Bilgisayar Mühendisliği (Lisans)");
        getContentPane().add(programlabel);
        programlabel.setBounds(390, 50, 280, 20);

        donemlabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        donemlabel.setForeground(new java.awt.Color(255, 255, 255));
        donemlabel.setText("3");
        getContentPane().add(donemlabel);
        donemlabel.setBounds(390, 80, 60, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ınterfaceprojem/labelbilgi.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 750, 121);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ınterfaceprojem/sollabel.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 135, 390);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ınterfaceprojem/kısayollabel.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 130, 600, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ınterfaceprojem/arkaplan2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(öğrenciBilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(öğrenciBilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(öğrenciBilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(öğrenciBilgi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               öğrenciBilgi a=new öğrenciBilgi();
                a.setVisible(true);
                a.setBounds(80, 80, 785, 570);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adlabel;
    private javax.swing.JLabel bolumlabel;
    private javax.swing.JLabel donemlabel;
    private javax.swing.JLabel fakultelabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nolabel;
    private javax.swing.JLabel programlabel;
    private javax.swing.JLabel sınıflabel;
    private javax.swing.JLabel tclabel;
    // End of variables declaration//GEN-END:variables
}
