/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ınterfaceprojem;

/**
 *
 * @author Berkant
 */
public class öğrenciekle extends javax.swing.JFrame {

    /**
     * Creates new form öğrenciekle
     */
    public öğrenciekle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ınterfaceprojem/user.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 280, 280);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Öğrenci no");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 50, 80, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("T.C kimlik no");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 90, 80, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Adı soyadı");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 130, 80, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Sınıf");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 170, 70, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Fakülte");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 210, 80, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Bölüm");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 250, 70, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Program");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 290, 80, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Dönem");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 330, 80, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Şifre");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 370, 70, 15);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(510, 40, 190, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(510, 80, 190, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(510, 120, 190, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(510, 360, 190, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(510, 160, 190, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mühendislik Fakültesi", "Mimarlık Fakültesi", "Eğitim Fakültesi", " " }));
        jComboBox2.setSelectedIndex(-1);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(510, 200, 190, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elektrik Elektronik Mühendisliği", "Bilgisayar Mühendisliği", "İnşaat Mühendisliği", "Makina Mühendisliği", "Çevre Mühendisliği", "Gıda Mühendisliği", "Matematik Öğretmenliği", "Mimarlık", " ", " " }));
        jComboBox3.setSelectedIndex(-1);
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(510, 240, 190, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", " " }));
        jComboBox4.setSelectedIndex(-1);
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(510, 320, 190, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bilgisayar Mühendisliği (İngilizce)", "Bilgisayar Mühendisliğİ (Lisans)", "Elektrik Elektronik Mühendisliği (Lisans)", "Makina Mühendisliği (Lisans)", "İnşaat Mühendisliği (Lisans)", "Çevre Mühendisliği (Lisans)", "Gıda Mühendisliği (Lisans)", "Matematik Öğretmenliği (Lisans)", "Mimarlık (İngilizce)", "Mimarlık (Lisans)" }));
        jComboBox5.setSelectedIndex(-1);
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(510, 280, 190, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Ekle");
        getContentPane().add(jButton1);
        jButton1.setBounds(720, 140, 90, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Temizle");
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 290, 90, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Güncelle");
        getContentPane().add(jButton3);
        jButton3.setBounds(720, 190, 90, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Sil");
        getContentPane().add(jButton4);
        jButton4.setBounds(720, 240, 90, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Göster");
        getContentPane().add(jButton5);
        jButton5.setBounds(720, 90, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ınterfaceprojem/arkaplan3.JPG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(öğrenciekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(öğrenciekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(öğrenciekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(öğrenciekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new öğrenciekle().setVisible(true);
                new öğrenciekle().setSize(820,420);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
